on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual runs

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Gitleaks
      run: |
        # Download gitleaks binary for Linux (ensure it's the correct version for the runner architecture)
        curl -sSL https://github.com/zricethezav/gitleaks/releases/download/v8.1.0/gitleaks-linux-amd64 -o /usr/local/bin/gitleaks
        # Verify the download file type
        file /usr/local/bin/gitleaks
        # Set executable permissions
        chmod +x /usr/local/bin/gitleaks

    - name: Verify Gitleaks Installation
      run: |
        # Check if gitleaks works by showing the version
        gitleaks --version

    - name: Run Gitleaks
      run: |
        gitleaks detect --source .github/test_files --report-format json --report-path gitleaks_report.json

    - name: Run n0s1
      run: |
        n0s1 scan --source .github/test_files --output n0s1_report.json

    - name: Combine Results
      run: |
        jq -s '.[0] * .[1]' gitleaks_report.json n0s1_report.json > combined_report.json
    
    - name: Commit and Push Results
      run: |
        git config --local user.email "you@example.com"
        git config --local user.name "GitHub Actions"
        git add combined_report.json
        git commit -m "Update combined scan results"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
